### ISSUE TITLE
The Big Stars' directional arrows disappear from the minimap after the big star does when collected

### ISSUE THREAD

**Issue by AprilShade** [ipodtouch0218/NSMB-MarioVsLuigi#337]
## Description
When a Big Star is collected, its directional arrow on the minimap disappears noticeably later than the big star itself.

## Game Version
v2.0.1.0, v2.0.2.0, v2.0.3.0, v2.0.4.1

## Steps to reproduce
1. Start a game on a map with star height indicators; Beach, Ice, etc.
2. Watch the big star and its arrow on the map
3. Collect the big star

## Expected Results
The big star and its arrow should disappear at the same time.

**Comment by ipodtouch0218** [comment]
Fixed in next patch

**Comment by ipodtouch0218** [comment]
Fixed in v2.0.2.0 hotfix

**Comment by AprilShade** [comment]
Not fixed. 

<img width="102" height="59" alt="Image" src="https://github.com/user-attachments/assets/ca332283-12d8-4f63-9e78-0b07b0cca64e" />

**Comment by AprilShade** [comment]
Still an issue in v2.0.4.1. Can this issue be reopened?

**Comment by ipodtouch0218** [comment]
Should be fixed for v2.2.0.0, needs online testing though.
