### ISSUE TITLE
Shells don't skip one-block-gaps after destroying a brick

### ISSUE THREAD

**Issue by GammelSami** [ipodtouch0218/NSMB-MarioVsLuigi#74]
Compairison video:

https://user-images.githubusercontent.com/39372285/179752912-4bf74637-d449-472a-9753-c1bd45abe54f.mp4

**Comment by ipodtouch0218** [comment]
Will be fixed in v1.6.8.0-beta

**Comment by ipodtouch0218** [comment]
Fixed in release [v1.6.8.0-beta](https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/releases/tag/v1.6.8.0-beta)

**Comment by GammelSami** [comment]
Now only works sometimes. Out of 7 tries 2 where still buggy.

https://user-images.githubusercontent.com/39372285/180664364-c767d8e4-62ee-4c05-88a3-d2dfb3dc6071.mp4

**Comment by ipodtouch0218** [comment]
Should be fully fixed in v1.8.0.0-beta
